version: '3.7'

services:
  database_ignite: 
    image: mysql:8.0.29
    container_name: database_ignite
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'ignite_database'
    volumes:
      - data:/var/lib/mysql

  app:
    build: .
    container_name: ignite
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
        - database_ignite
volumes:
  data:
    driver: local
