version: '3.7'

services:
  database_ignite:
    image: mysql:8.0.29
    container_name: database_ignite
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'ignite_database'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - pgdata:/var/lib/mysql
    network_mode: host
  app:
    build: .
    container_name: ignite
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
